version: '3'

services:
    web_ft:
        restart: always
        build: .
        volumes:
            - ./:/var/www/
        networks:
            - rede_ft

    nginx_ft:
        build: ./.docker/nginx/
        restart: always
        ports:
            - "8060:80"
        volumes:
            - ./:/var/www/
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web_ft
        networks:
             - rede_ft

    mysql_ft:
        image: mysql:5.7
        ports:
            - "8062:3306"
        volumes:
            - ./MySQL:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=Ft#2022Egpce
            - MYSQL_DATABASE=db_ft
        networks:
            - rede_ft

    phpmyadmin_ft:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysql_ft
        ports:
            - "8061:80"
        environment:
            - PMA_ARBITRARY=1
        networks:
            - rede_ft

volumes:
  MySQL:

networks:
  rede_ft:
    driver: bridge
